-- WAGWAN production-oriented Supabase schema.
-- RERUN-SAFE: this script is designed to be executed on an existing WAGWAN Supabase project.
-- It does NOT drop tables or data. Existing policies are dropped/recreated by name.
-- Run this in Supabase SQL Editor.

create extension if not exists pgcrypto;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_type
        WHERE typname = 'user_role'
          AND typnamespace = 'public'::regnamespace
    ) THEN
        CREATE TYPE public.user_role AS ENUM ('customer','admin');
    END IF;
END
$$;
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_type
        WHERE typname = 'order_status'
          AND typnamespace = 'public'::regnamespace
    ) THEN
        CREATE TYPE public.order_status AS ENUM ('pending','confirmed','cancelled','delivered');
    END IF;
END
$$;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  role public.user_role not null default 'customer',
  created_at timestamptz not null default now()
);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, full_name) values (new.id, coalesce(new.raw_user_meta_data->>'full_name', new.email));
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists(select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin');
$$;

create table if not exists public.categories (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  is_active boolean not null default true,
  is_system boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.products (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  name text not null,
  category_id uuid references public.categories(id) on delete set null,
  color text,
  description text,
  details jsonb not null default '[]'::jsonb,
  price numeric(12,2) not null check (price >= 0),
  compare_price numeric(12,2) check (compare_price is null or compare_price >= 0),
  promotion text,
  main_image_url text,
  is_active boolean not null default true,
  stock_s integer not null default 0 check (stock_s >= 0),
  stock_m integer not null default 0 check (stock_m >= 0),
  stock_l integer not null default 0 check (stock_l >= 0),
  stock_xl integer not null default 0 check (stock_xl >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.product_images (
  id uuid primary key default gen_random_uuid(),
  product_id uuid not null references public.products(id) on delete cascade,
  image_url text not null,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  order_number bigint generated by default as identity unique,
  first_name text not null,
  last_name text not null,
  phone text not null,
  address text not null,
  city text not null,
  status public.order_status not null default 'pending',
  payment_method text not null default 'COD' check (payment_method = 'COD'),
  subtotal numeric(12,2) not null check (subtotal >= 0),
  shipping numeric(12,2) not null default 0 check (shipping >= 0),
  total numeric(12,2) not null check (total >= 0),
  created_at timestamptz not null default now(),
  delivered_at timestamptz
);

create table if not exists public.order_items (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  product_id uuid not null references public.products(id) on delete restrict,
  product_name text not null,
  product_image_url text,
  size text not null check (size in ('S','M','L','XL')),
  quantity integer not null check (quantity > 0),
  unit_price numeric(12,2) not null check (unit_price >= 0),
  line_total numeric(12,2) not null check (line_total >= 0)
);

insert into public.categories (name,is_system) values
('Longsleeves',true),('T-Shirts',true),('Hoodies',true),('Shorts',true),('Jogging',true)
on conflict (name) do nothing;

insert into public.products (slug,name,category_id,color,description,details,price,main_image_url,stock_s,stock_m,stock_l,stock_xl)
select 'taste-longsleeve','TASTE LONGSLEEVE',c.id,'WHITE / RED',
'White longsleeve with the red WAGWAN signature on the front and the TASTE cherry artwork on the back.',
'["BOXY FIT","UNISEX","RIBBED CREWNECK","WIDE SLEEVES","ORGANIC PRE-SHRUNK COTTON FABRIC"]'::jsonb,239,'assets/taste-front-back.png',10,15,12,8
from public.categories c where c.name='Longsleeves'
on conflict (slug) do nothing;

insert into public.products (slug,name,category_id,color,description,details,price,main_image_url,stock_s,stock_m,stock_l,stock_xl)
select 'its-never-luck-longsleeve','IT''S NEVER LUCK LONGSLEEVE',c.id,'WHITE / CAMO',
'White longsleeve with the camouflage WAGWAN signature on the front and the IT’S NEVER LUCK IT’S ALWAYS GOD artwork on the back.',
'["BOXY FIT","UNISEX","RIBBED CREWNECK","WIDE SLEEVES","ORGANIC PRE-SHRUNK COTTON FABRIC"]'::jsonb,239,'assets/luck-front-back.png',15,20,10,12
from public.categories c where c.name='Longsleeves'
on conflict (slug) do nothing;

-- Replace the placeholder email below with YOUR own Supabase Auth email, then run once.
-- update public.profiles set role='admin' where id=(select id from auth.users where email='YOUR_ADMIN_EMAIL');

alter table public.profiles enable row level security;
alter table public.categories enable row level security;
alter table public.products enable row level security;
alter table public.product_images enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;

drop policy if exists "public read active categories" on public.categories;
create policy "public read active categories" on public.categories for select to anon,authenticated using (is_active = true);
drop policy if exists "admin manage categories" on public.categories;
create policy "admin manage categories" on public.categories for all to authenticated using (public.is_admin()) with check (public.is_admin());
drop policy if exists "public read active products" on public.products;
create policy "public read active products" on public.products for select to anon,authenticated using (is_active = true);
drop policy if exists "admin manage products" on public.products;
create policy "admin manage products" on public.products for all to authenticated using (public.is_admin()) with check (public.is_admin());
drop policy if exists "public read active product images" on public.product_images;
create policy "public read active product images" on public.product_images for select to anon,authenticated using (exists(select 1 from public.products p where p.id=product_images.product_id and p.is_active=true));
drop policy if exists "admin manage product images" on public.product_images;
create policy "admin manage product images" on public.product_images for all to authenticated using (public.is_admin()) with check (public.is_admin());
drop policy if exists "admin read profiles" on public.profiles;
create policy "admin read profiles" on public.profiles for select to authenticated using (public.is_admin() or id=auth.uid());
drop policy if exists "admin update profiles" on public.profiles;
create policy "admin update profiles" on public.profiles for update to authenticated using (public.is_admin()) with check (public.is_admin());
drop policy if exists "admin read orders" on public.orders;
create policy "admin read orders" on public.orders for select to authenticated using (public.is_admin());
drop policy if exists "admin update orders" on public.orders;
create policy "admin update orders" on public.orders for update to authenticated using (public.is_admin()) with check (public.is_admin());
drop policy if exists "admin read order items" on public.order_items;
create policy "admin read order items" on public.order_items for select to authenticated using (public.is_admin());
create or replace function public.create_cod_order(
  p_first_name text,
  p_last_name text,
  p_phone text,
  p_address text,
  p_city text,
  p_items jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  item jsonb;
  p public.products%rowtype;
  o public.orders%rowtype;
  requested_size text;
  requested_qty integer;
  current_stock integer;
  new_stock integer;
  sub numeric(12,2) := 0;
  ship numeric(12,2) := 0;
  line numeric(12,2);
  item_count integer;
begin
  if nullif(trim(p_first_name),'') is null or nullif(trim(p_last_name),'') is null or nullif(trim(p_phone),'') is null or nullif(trim(p_address),'') is null or nullif(trim(p_city),'') is null then
    raise exception 'Missing required customer information';
  end if;
  if jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items)=0 then raise exception 'Cart is empty'; end if;
  item_count := jsonb_array_length(p_items);

  for item in select * from jsonb_array_elements(p_items) loop
    select * into p from public.products where id=(item->>'product_id')::uuid and is_active=true for update;
    if not found then raise exception 'Product not available'; end if;
    requested_size := upper(item->>'size'); requested_qty := (item->>'quantity')::integer;
    if requested_size not in ('S','M','L','XL') or requested_qty <= 0 then raise exception 'Invalid item'; end if;
    current_stock := case requested_size when 'S' then p.stock_s when 'M' then p.stock_m when 'L' then p.stock_l else p.stock_xl end;
    if current_stock < requested_qty then raise exception 'Out of stock: % size %', p.name, requested_size; end if;
    line := p.price * requested_qty; sub := sub + line;
  end loop;

  insert into public.orders(first_name,last_name,phone,address,city,status,payment_method,subtotal,shipping,total)
  values(trim(p_first_name),trim(p_last_name),trim(p_phone),trim(p_address),trim(p_city),'pending','COD',sub,ship,sub+ship)
  returning * into o;

  for item in select * from jsonb_array_elements(p_items) loop
    select * into p from public.products where id=(item->>'product_id')::uuid for update;
    requested_size := upper(item->>'size'); requested_qty := (item->>'quantity')::integer;
    line := p.price * requested_qty;
    insert into public.order_items(order_id,product_id,product_name,product_image_url,size,quantity,unit_price,line_total)
    values(o.id,p.id,p.name,p.main_image_url,requested_size,requested_qty,p.price,line);
    case requested_size
      when 'S' then update public.products set stock_s=stock_s-requested_qty, updated_at=now() where id=p.id;
      when 'M' then update public.products set stock_m=stock_m-requested_qty, updated_at=now() where id=p.id;
      when 'L' then update public.products set stock_l=stock_l-requested_qty, updated_at=now() where id=p.id;
      when 'XL' then update public.products set stock_xl=stock_xl-requested_qty, updated_at=now() where id=p.id;
    end case;
  end loop;

  return jsonb_build_object('id',o.id,'order_number',o.order_number,'total',o.total);
end;
$$;

revoke all on function public.create_cod_order(text,text,text,text,text,jsonb) from public;
grant execute on function public.create_cod_order(text,text,text,text,text,jsonb) to anon,authenticated;

-- Storage: create a bucket named product-images in Storage UI (public bucket), then use these policies.
-- Public visitors can read images; only admins can upload/update/delete.
drop policy if exists "public read product images" on storage.objects;
create policy "public read product images" on storage.objects for select to anon,authenticated using (bucket_id='product-images');
drop policy if exists "admin upload product images" on storage.objects;
create policy "admin upload product images" on storage.objects for insert to authenticated with check (bucket_id='product-images' and public.is_admin());
drop policy if exists "admin update product images" on storage.objects;
create policy "admin update product images" on storage.objects for update to authenticated using (bucket_id='product-images' and public.is_admin()) with check (bucket_id='product-images' and public.is_admin());
drop policy if exists "admin delete product images" on storage.objects;
create policy "admin delete product images" on storage.objects for delete to authenticated using (bucket_id='product-images' and public.is_admin());
-- Recommended hardening: admins cannot promote other accounts from the browser.
drop policy if exists "admin update profiles" on public.profiles;

-- Additional server-side validation for COD order RPC.
create or replace function public.create_cod_order(
  p_first_name text,
  p_last_name text,
  p_phone text,
  p_address text,
  p_city text,
  p_items jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  item jsonb;
  p public.products%rowtype;
  o public.orders%rowtype;
  requested_size text;
  requested_qty integer;
  current_stock integer;
  sub numeric(12,2) := 0;
  ship numeric(12,2) := 0;
begin
  if length(trim(p_first_name)) not between 1 and 80 or length(trim(p_last_name)) not between 1 and 80 then raise exception 'Invalid name'; end if;
  if length(trim(p_address)) not between 1 and 300 or length(trim(p_city)) not between 1 and 100 then raise exception 'Invalid address or city'; end if;
  if trim(p_phone) !~ '^(\+212|0)[67][0-9]{8}$' then raise exception 'Invalid Moroccan phone number'; end if;
  if jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items)=0 or jsonb_array_length(p_items)>30 then raise exception 'Invalid cart'; end if;

  for item in select * from jsonb_array_elements(p_items) loop
    select * into p from public.products where id=(item->>'product_id')::uuid and is_active=true for update;
    if not found then raise exception 'Product not available'; end if;
    requested_size := upper(item->>'size'); requested_qty := (item->>'quantity')::integer;
    if requested_size not in ('S','M','L','XL') or requested_qty < 1 or requested_qty > 50 then raise exception 'Invalid item'; end if;
    current_stock := case requested_size when 'S' then p.stock_s when 'M' then p.stock_m when 'L' then p.stock_l else p.stock_xl end;
    if current_stock < requested_qty then raise exception 'Out of stock: % size %', p.name, requested_size; end if;
    sub := sub + (p.price * requested_qty);
  end loop;

  insert into public.orders(first_name,last_name,phone,address,city,status,payment_method,subtotal,shipping,total)
  values(trim(p_first_name),trim(p_last_name),trim(p_phone),trim(p_address),trim(p_city),'pending','COD',sub,ship,sub+ship)
  returning * into o;

  for item in select * from jsonb_array_elements(p_items) loop
    select * into p from public.products where id=(item->>'product_id')::uuid for update;
    requested_size := upper(item->>'size'); requested_qty := (item->>'quantity')::integer;
    insert into public.order_items(order_id,product_id,product_name,product_image_url,size,quantity,unit_price,line_total)
    values(o.id,p.id,p.name,p.main_image_url,requested_size,requested_qty,p.price,p.price*requested_qty);
    case requested_size
      when 'S' then update public.products set stock_s=stock_s-requested_qty,updated_at=now() where id=p.id;
      when 'M' then update public.products set stock_m=stock_m-requested_qty,updated_at=now() where id=p.id;
      when 'L' then update public.products set stock_l=stock_l-requested_qty,updated_at=now() where id=p.id;
      when 'XL' then update public.products set stock_xl=stock_xl-requested_qty,updated_at=now() where id=p.id;
    end case;
  end loop;
  return jsonb_build_object('id',o.id,'order_number',o.order_number,'total',o.total);
end;
$$;
revoke all on function public.create_cod_order(text,text,text,text,text,jsonb) from public;
grant execute on function public.create_cod_order(text,text,text,text,text,jsonb) to anon,authenticated;

-- Seed the exact secondary reference assets used by the original HTML build.
insert into public.product_images(product_id,image_url,sort_order)
select p.id, x.url, x.ord
from public.products p
cross join lateral (values
  ('assets/taste-detail.png',1),('assets/taste-label.png',2)
) x(url,ord)
where p.slug='taste-longsleeve'
on conflict do nothing;
insert into public.product_images(product_id,image_url,sort_order)
select p.id, x.url, x.ord
from public.products p
cross join lateral (values
  ('assets/luck-logo-detail.png',1),('assets/luck-cuff.png',2),('assets/luck-label.png',3)
) x(url,ord)
where p.slug='its-never-luck-longsleeve'
on conflict do nothing;

delete from public.product_images where image_url in ('assets/taste-detail.png','assets/taste-label.png','assets/luck-logo-detail.png','assets/luck-cuff.png','assets/luck-label.png');
insert into public.product_images(product_id,image_url,sort_order)
select p.id, 'assets/taste-detail.png',1 from public.products p where p.slug='taste-longsleeve';
insert into public.product_images(product_id,image_url,sort_order)
select p.id, 'assets/taste-label.png',2 from public.products p where p.slug='taste-longsleeve';
insert into public.product_images(product_id,image_url,sort_order)
select p.id, 'assets/luck-logo-detail.png',1 from public.products p where p.slug='its-never-luck-longsleeve';
insert into public.product_images(product_id,image_url,sort_order)
select p.id, 'assets/luck-cuff.png',2 from public.products p where p.slug='its-never-luck-longsleeve';
insert into public.product_images(product_id,image_url,sort_order)
select p.id, 'assets/luck-label.png',3 from public.products p where p.slug='its-never-luck-longsleeve';

-- Realtime for the dashboard/store admin. Safe to run repeatedly.
do $$
begin
  begin execute 'alter publication supabase_realtime add table public.orders'; exception when duplicate_object then null; end;
  begin execute 'alter publication supabase_realtime add table public.products'; exception when duplicate_object then null; end;
  begin execute 'alter publication supabase_realtime add table public.categories'; exception when duplicate_object then null; end;
end $$;


-- ========================= WAGWAN DATA EXTENSIONS =========================
-- Compatibility tables used by the admin/data model.
create table if not exists public.product_sizes (
  id uuid primary key default gen_random_uuid(),
  product_id uuid not null references public.products(id) on delete cascade,
  size text not null check (size in ('S','M','L','XL')),
  stock integer not null default 0 check (stock >= 0),
  created_at timestamptz not null default now(),
  unique(product_id,size)
);
alter table public.product_sizes enable row level security;
drop policy if exists "public read active product sizes" on public.product_sizes;
create policy "public read active product sizes" on public.product_sizes for select to anon,authenticated using (exists(select 1 from public.products p where p.id=product_sizes.product_id and p.is_active=true));
drop policy if exists "admin manage product sizes" on public.product_sizes;
create policy "admin manage product sizes" on public.product_sizes for all to authenticated using (public.is_admin()) with check (public.is_admin());
create or replace function public.sync_product_sizes()
returns trigger
language plpgsql
security definer set search_path=public
as $$
begin
  insert into public.product_sizes(product_id,size,stock) values
    (new.id,'S',new.stock_s),(new.id,'M',new.stock_m),(new.id,'L',new.stock_l),(new.id,'XL',new.stock_xl)
  on conflict(product_id,size) do update set stock=excluded.stock;
  return new;
end;
$$;
drop trigger if exists trg_sync_product_sizes on public.products;
create trigger trg_sync_product_sizes after insert or update of stock_s,stock_m,stock_l,stock_xl on public.products for each row execute function public.sync_product_sizes();
insert into public.product_sizes(product_id,size,stock)
select p.id,v.size,v.stock from public.products p cross join lateral (values ('S',p.stock_s),('M',p.stock_m),('L',p.stock_l),('XL',p.stock_xl)) v(size,stock)
on conflict(product_id,size) do update set stock=excluded.stock;

create table if not exists public.customers (
  id uuid primary key default gen_random_uuid(),
  full_name text not null,
  phone text not null unique,
  city text,
  orders_count integer not null default 0 check (orders_count >= 0),
  total_spent numeric(12,2) not null default 0 check (total_spent >= 0),
  status text not null default 'Normal' check (status in ('Normal','Actif')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table public.customers enable row level security;
drop policy if exists "admin read customers" on public.customers;
create policy "admin read customers" on public.customers for select to authenticated using (public.is_admin());
drop policy if exists "admin manage customers" on public.customers;
create policy "admin manage customers" on public.customers for all to authenticated using (public.is_admin()) with check (public.is_admin());
-- Public feedback is submitted as pending and can only be published by an admin.
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_type
    WHERE typname = 'feedback_status'
      AND typnamespace = 'public'::regnamespace
  ) THEN
    CREATE TYPE public.feedback_status AS ENUM ('pending','approved','rejected');
  END IF;
END
$$;

create table if not exists public.feedback (
  id uuid primary key default gen_random_uuid(),
  customer_name text not null check (char_length(trim(customer_name)) between 2 and 60),
  city text not null check (char_length(trim(city)) between 2 and 60),
  rating integer not null check (rating between 1 and 5),
  comment text not null check (char_length(trim(comment)) between 5 and 700),
  status public.feedback_status not null default 'pending',
  created_at timestamptz not null default now(),
  moderated_at timestamptz
);
alter table public.feedback enable row level security;
drop policy if exists "public read approved feedback" on public.feedback;
create policy "public read approved feedback" on public.feedback for select to anon,authenticated using (status='approved');
drop policy if exists "public submit pending feedback" on public.feedback;
create policy "public submit pending feedback" on public.feedback for insert to anon,authenticated with check (status='pending');
drop policy if exists "admin read all feedback" on public.feedback;
create policy "admin read all feedback" on public.feedback for select to authenticated using (public.is_admin());
drop policy if exists "admin moderate feedback" on public.feedback;
create policy "admin moderate feedback" on public.feedback for update to authenticated using (public.is_admin()) with check (public.is_admin());
drop policy if exists "admin delete feedback" on public.feedback;
create policy "admin delete feedback" on public.feedback for delete to authenticated using (public.is_admin());
-- Backfill the dedicated customer table when upgrading an existing project.
insert into public.customers(full_name,phone,city,orders_count,total_spent,status,updated_at)
select trim(o.first_name||' '||o.last_name), trim(o.phone), (array_agg(o.city order by o.created_at desc))[1], count(*)::integer, coalesce(sum(o.total),0), case when count(*)>=3 then 'Actif' else 'Normal' end, now()
from public.orders o
group by trim(o.phone), trim(o.first_name||' '||o.last_name)
on conflict(phone) do update set
  full_name=excluded.full_name, city=excluded.city, orders_count=excluded.orders_count, total_spent=excluded.total_spent, status=excluded.status, updated_at=now();

-- Keep the dedicated customer table in sync when a COD order is created.
create or replace function public.upsert_customer_from_order()
returns trigger language plpgsql security definer set search_path=public as $$
begin
  insert into public.customers(full_name,phone,city,orders_count,total_spent,status,updated_at)
  values(trim(new.first_name||' '||new.last_name),trim(new.phone),trim(new.city),1,new.total,'Normal',now())
  on conflict(phone) do update set
    full_name=excluded.full_name,
    city=excluded.city,
    orders_count=public.customers.orders_count+1,
    total_spent=public.customers.total_spent+excluded.total,
    status=case when public.customers.orders_count+1>=3 then 'Actif' else 'Normal' end,
    updated_at=now();
  return new;
end;
$$;
drop trigger if exists trg_upsert_customer_from_order on public.orders;
create trigger trg_upsert_customer_from_order after insert on public.orders for each row execute function public.upsert_customer_from_order();

-- Realtime feedback for public approval and the admin moderation queue.
do $$ begin
  begin execute 'alter publication supabase_realtime add table public.feedback'; exception when duplicate_object then null; end;
  begin execute 'alter publication supabase_realtime add table public.customers'; exception when duplicate_object then null; end;
  begin execute 'alter publication supabase_realtime add table public.product_sizes'; exception when duplicate_object then null; end;
end $$;
