import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
const SUPABASE_URL=Deno.env.get("SUPABASE_URL")!;const SERVICE_ROLE=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;const SIGNING_KEY=Deno.env.get("SENDIT_WEBHOOK_SIGNING_KEY")!;
const sb=()=>createClient(SUPABASE_URL,SERVICE_ROLE);
const enc=new TextEncoder();
function hex(buf:ArrayBuffer){return Array.from(new Uint8Array(buf)).map(b=>b.toString(16).padStart(2,"0")).join("")}
async function hmac(body:string){const key=await crypto.subtle.importKey("raw",enc.encode(SIGNING_KEY),{name:"HMAC",hash:"SHA-256"},false,["sign"]);return hex(await crypto.subtle.sign("HMAC",key,enc.encode(body)))}
function timingSafeEqual(a:string,b:string){if(a.length!==b.length)return false;let r=0;for(let i=0;i<a.length;i++)r|=a.charCodeAt(i)^b.charCodeAt(i);return r===0}
function mapStatus(s:string){switch(s){case"PICKEDUP":return"picked_up";case"TRANSIT":return"in_transit";case"WAREHOUSE":return"warehouse";case"DISTRIBUTED":return"distributed";case"DELIVERING":return"delivering";case"DELIVERED":return"delivered";case"CANCELED":case"REJECTED":case"UNREACHABLE":case"POSTPONED":return"exception";default:return"created"}}
function cors(){return {"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"content-type,x-sendit-signature","Access-Control-Allow-Methods":"POST,OPTIONS"}}
Deno.serve(async(req)=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors()});if(req.method!=="POST")return new Response("Method Not Allowed",{status:405,headers:cors()});try{if(!SIGNING_KEY)throw new Error("SENDIT_WEBHOOK_SIGNING_KEY is not configured");const raw=await req.text();const signature=(req.headers.get("X-Sendit-Signature")||"").trim();const expected=await hmac(raw);if(!signature||!timingSafeEqual(signature.toLowerCase(),expected.toLowerCase()))return new Response(JSON.stringify({error:"Invalid signature"}),{status:401,headers:{...cors(),"Content-Type":"application/json"}});const p=JSON.parse(raw);if(p?.event!=="delivery.status.update")return new Response(JSON.stringify({success:true,ignored:true}),{headers:{...cors(),"Content-Type":"application/json"}});const code=String(p.code||"").trim();const newStatus=String(p.newStatus||"").trim();if(!code||!newStatus)throw new Error("Invalid webhook payload");const admin=sb();const {data:shipment,error:findErr}=await admin.from("delivery_shipments").select("*").eq("sendit_code",code).single();if(findErr||!shipment)return new Response(JSON.stringify({success:true,ignored:true,reason:"unknown delivery code"}),{headers:{...cors(),"Content-Type":"application/json"}});await admin.from("delivery_tracking_events").insert({shipment_id:shipment.id,sendit_code:code,old_status:p.oldStatus||null,new_status:newStatus,last_action_at_text:p.lastActionAt||null,message:p.message||null,proof_image_url:p.proofImage||null,deliver_by:p.deliverBy||null,counter_unreachable:p.counterUnreachable==null?null:Number(p.counterUnreachable),raw_payload:p});const patch:any={sendit_status:newStatus,internal_status:mapStatus(newStatus),last_action_at_text:p.lastActionAt||shipment.last_action_at_text,proof_image_url:p.proofImage||shipment.proof_image_url,deliver_by:p.deliverBy||shipment.deliver_by,counter_unreachable:p.counterUnreachable==null?shipment.counter_unreachable:Number(p.counterUnreachable),raw_last_payload:p,updated_at:new Date().toISOString()};if(newStatus==="PICKEDUP"&&!shipment.picked_up_at)patch.picked_up_at=new Date().toISOString();if(newStatus==="DELIVERED"&&!shipment.delivered_at)patch.delivered_at=new Date().toISOString();if(newStatus==="CANCELED"&&!shipment.canceled_at)patch.canceled_at=new Date().toISOString();const {error:upErr}=await admin.from("delivery_shipments").update(patch).eq("id",shipment.id);if(upErr)throw upErr;if(newStatus==="DELIVERED")await admin.from("orders").update({status:"delivered",delivered_at:new Date().toISOString()}).eq("id",shipment.order_id);return new Response(JSON.stringify({success:true,processed:true,code,newStatus}),{headers:{...cors(),"Content-Type":"application/json"}})}catch(e){const msg=e instanceof Error?e.message:String(e);console.error(msg);return new Response(JSON.stringify({error:msg}),{status:400,headers:{...cors(),"Content-Type":"application/json"}})}});
